### PR TITLE
Bug/2410 fix lh a11y issues

### LINKED ISSUE #2410: Fix accessibility errors found on lighthouse reports for talentSearch app
Fix accessibility problems found in lighthouse report.
- [ ] Fix contrast ratio on specified elements (MultiSelect components, Footer)
image
- [ ] Fix associated label for MultiSelect buttons 
image
- [ ] Fix contrast ratio on [request page](https://talent.canada.ca/en/talent/request) 
image

### PR DESCRIPTION
**Pull request by esizer**
## Summary

This fixes the issues found by lighthouse on the `/talent/search` and `/talent/request` pages.

Resolves #2410 

### Multi-Select Fields

The multi-select fields, using `react-select`, were missing a label. We have added an `aria-label` attribute using the label passed in as a prop to remedy this.

## Colour Contrast

There were a few spots where the colour contrast ratio was not being met. These include the placeholders for the multi-select fields, required indicator on inputs, date modified in the footer.

### Multi-Select Fields

The placeholders were made slightly darker (hydrogran darkgray `#646464`)  which resulted in a colour contrast ratio of 5.91:1.

multi-select-contrast

### Required Input Indicator

Previously, this used pure red (`#ff0000`) and was modified slightly to `#e90101` to get to a contrast ratio of 4.69:1.

required-input-label-colour-contrast

### Date Modified

This was using the default gray set in hydrogen (`#B9B9B9`) but was darkened to the darkgray (`#646464`) to get a ratio of 5.47:1.

footer-colour-contrast

## Results

Both pages now score 100/100 on lighthouse accessibility audits.

### Search Page 

search-page-audit

### Request Page

request-page-audit

### CODE REVIEW

**Comment by RVany** [comment]
data-h2-font-color="b([dark]gray)"
            data-h2-font-color="b(darkgray)" @esizer I am just wondering are both of the colors are different? I think I used first option in my current PR. Will it affect in any way?

**Comment by esizer** [comment]
@RVany There is a specific colour in the `frontend/common/hydrogren.config.json` file which is slightly darker than `[dark]gray` which was required to meet the colour contrast ratio. Depending on the background colour, I don't think it should be an issue.

File: frontend/common/src/components/form/MultiSelect/MultiSelect.tsx [hunk 1]
```diff
@@ -69,7 +69,13 @@ export const MultiSelect: React.FunctionComponent<MultiSelectProps> = ({
                 }
                 placeholder={placeholder}
                 options={options}
-                styles={{}}
+                aria-label={label}
+                styles={{
+                  placeholder: (provided) => ({
+                    ...provided,
+                    color: `#646464`,
```
Comment (petertgiles) [inline frontend/common/src/components/form/MultiSelect/MultiSelect.tsx:76]: Having a raw colour hex in here feels a little weird but I doubt this could be handled in hydrogen and if it's not being used anywhere else it doesn't make sense to have it in the shared CSS file. :shrug:

**Review by petertgiles — APPROVED** [review]
Looks super nice.  I confirm that I see a 100% on the lighthouse accessiblity scan as well.

File: frontend/common/src/components/form/MultiSelect/MultiSelect.tsx (hunk 1 above)
Comment (esizer) [reply frontend/common/src/components/form/MultiSelect/MultiSelect.tsx:76]: Yeah, I agree. I'm not super happy about doing it this way but I reviewed both `react-select` and `hydrogen` and couldn't find a better way. Unfortunately, `react-select` seems to want it passed as a style object and not `className`.

Comment (tristan-orourke) [reply frontend/common/src/components/form/MultiSelect/MultiSelect.tsx:76]: My only comment would be that this might be a good place for a comment explaining that a one-off colour was used here for a11y purposes.
