### PR TITLE
Bug/4541 filter advice recommendations change

### LINKED ISSUE #4541: List only the optional filters on the Results section to improve the search results
### Problem 

1.  Classification filter is now required filter. It should not show up on the Results section like in the screen shot to improve the search results.

2. Filters like below doesn't show up in this section when selected. This needs to be fixed as well 

- Education requirement for the job , 
- Working language ability,
- Employment Duration,
- Employment Equity,
- Skills as filters 

( Do not add Work location as it is a required filter )

### PR DESCRIPTION
**Pull request by vd1992**
closes #4541 
changes the recommendations building to only include optional filter selections
in both regular and deprecated

testing:
play around with `/en/search` in both regular and deprecated environments, adding filters and clicking links
I find changing this line to only render the one you want a more convenient way to switch between them

image

### CODE REVIEW

**Comment by vd1992** [comment]
**### Translations**
Intl strings to be translated below, I will send them after someone affirms that they look right (none missing and no typos) to avoid being annoying 
Descriptions appear intentionally omitted on the SearchAdvice pages, continuing that, probably for ease of reuse

File: frontend/talentsearch/src/js/components/search/SearchFilterAdvice.tsx [hunk 1]
```diff
@@ -1,61 +1,150 @@
...
+        <a
+          href="#skillFilter"
           data-h2-color="base(dt-primary)"
           data-h2-font-weight="base(700)"
         >
           {intl.formatMessage(
             {
-              defaultMessage:
-                "Conditions of Employment ({operationalRequirementFilterCount})",
-              id: "ky585k",
```
Comment (vd1992) [inline frontend/talentsearch/src/js/components/search/SearchFilterAdvice.tsx:51]: same as

File: frontend/talentsearch/src/js/components/search/SearchFilterAdvice.tsx [hunk 2]
```diff
@@ -1,61 +1,150 @@
...
           data-h2-color="base(dt-primary)"
           data-h2-font-weight="base(700)"
         >
           {intl.formatMessage(
             {
               defaultMessage:
-                "Classification Filters ({classificationFilterCount})",
-              id: "LRysDa",
+                "Conditions of Employment ({operationalRequirementFilterCount})",
+              id: "ky585k",
```
Comment (vd1992) [inline frontend/talentsearch/src/js/components/search/SearchFilterAdvice.tsx:46]: same

**Comment by esizer** [comment]
> Intl strings to be translated below, I will send them after someone affirms that they look right (none missing, no typos or wording issues) to avoid being annoying

I'd get some more input but, I don't think we need to specific "selection". I think just using the labels like the following would be fine:

- Language ability
- Employment duration
- Employment equity (2)

> Descriptions appear intentionally omitted on the SearchAdvice pages, continuing that, probably for ease of reuse

Also, I think maybe the missing descriptions was possibly not intentional. I believe the descriptions are important for context when sent off for translation.

**Comment by petertgiles** [comment]
> I believe the descriptions are important for context when sent off for translation.

Agreed

File: frontend/talentsearch/src/js/components/search/SearchFilterAdvice.tsx [hunk 3]
```diff
@@ -1,61 +1,150 @@
...
+            { operationalRequirementFilterCount },
           )}
         </a>
       ),
     });
   }
-  if (operationalRequirementFilterCount > 0) {
+
+  if (educationSelection) {
     recommendations.push({
```
Comment (petertgiles) [inline frontend/talentsearch/src/js/components/search/SearchFilterAdvice.tsx:56]: It might be nice to do this in a more functional way, without the array pushes.  I'm thinking something like this:
https://blog.agney.dev/optional-spreading/#spreading-into-an-array

File: frontend/talentsearch/src/js/components/search/SearchFilterAdvice.tsx [hunk 4]
```diff
@@ -1,61 +1,150 @@
...
+    recommendations.push({
+      key: "employmentEquityFilter",
+      link: (
+        <a
+          href="#employmentEquityFilter"
+          data-h2-color="base(dt-primary)"
+          data-h2-font-weight="base(700)"
+        >
+          {intl.formatMessage({
+            defaultMessage: "Equity selection",
```
Comment (petertgiles) [inline frontend/talentsearch/src/js/components/search/SearchFilterAdvice.tsx:119]: It might be nice to add the number of filters in parenthesis the way CoE and Skills do it.

**Review by petertgiles — COMMENTED** [review]
Nice!  It works well for me on both the old and new pages.  I won't approve yet since I know you're working through copy and translation.  In the meantime, I've added a few suggestions.

**Comment by vd1992** [comment]
Please confirm if the wording for defaultMessage lines below looks okay to you
@Jerryescandon 

```
defaultMessage: "Diploma required",
description: "Diploma required",
id: "w1/0Cd",

defaultMessage: "Language ability",
description: "Language ability",
id: "mKzQwr",

defaultMessage: "Employment duration",
description: "Employment duration",
id: "hRe0yl",

defaultMessage: "Employment equity ({equityFiltersActive})",
description: "Employment equity with a number in parentheses",
id: "dE2WB1",

defaultMessage: "Skills selected ({skillCount})",
id: "RNI+IH",
description: "Skills selected and then a number in parentheses",

```

File: frontend/talentsearch/src/js/components/search/SearchFilterAdvice.tsx (hunk 4 above)
Comment (vd1992) [reply frontend/talentsearch/src/js/components/search/SearchFilterAdvice.tsx]: sure https://github.com/GCTC-NTGC/gc-digital-talent/pull/4553/commits/f21f9af77d266d060eb9940a45fb5429428d7dc6

**Comment by Jerryescandon** [comment]
Yup, these look good to me.

Context may be way better, but tbh that feels like it should instead be a fancier interaction using pills. But that just sounds like a problem for future Jerbo to design and future Gray to prioritize. Lets keep this simple for now.

**Comment by vd1992** [comment]
Thank you!
