### PR TITLE
Bug - 2964 - Add lang Attribute to i18n Toggle

### LINKED ISSUE #2964: Language toggle link missing lang attribute
## Description

> Any content in a language other than the page language must be marked up accordingly. For the language toggle link on the top right, its code should be as follows:

`<a href="/fr" lang="fr">Français</a>`

### PR DESCRIPTION
**Pull request by esizer**
Resolves #2964 

## Summary

This adds the `lang` attribute to the i18n toggle to improve accessibility by allowing assistive technology to know that the language in this link does not match that of the page improving pronunciation. 

## Note

Inorder to do this, we have updated the prop types for the `<Link />` component to use ` React.HTMLProps<HTMLAnchorElement>`

### CODE REVIEW

File: frontend/common/src/helpers/router.tsx [hunk 1]
```diff
@@ -1,6 +1,12 @@
 import { createBrowserHistory, Location, Path, State } from "history";
 import UniversalRouter, { Routes } from "universal-router";
-import React, { useState, useEffect, useMemo, ReactElement } from "react";
+import React, {
+  useState,
+  useEffect,
+  useMemo,
+  ReactElement,
+  HTMLAttributes,
+} from "react";
```
Comment (vd1992) [inline frontend/common/src/helpers/router.tsx:9]: seeing a linting thing here 😆

Comment (esizer) [reply frontend/common/src/helpers/router.tsx]: I deleted that, what the heck lol 😭 

Resolved with [remove unused imports](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3027/commits/5bca08645f2ac36fa1a21175dd6ac790608bc6f4)

**Comment by vd1992** [comment]
I'm not too familiar with what the issue is about, @mnigh could tell if the matter is resolved per standards?

**Review by yonikid15 — APPROVED** [review]
Looks good to me!
