### PR TITLE
Use root app url in login redirect

### LINKED ISSUE #2044: Bug - auth deep linking doesn't work when app hosted behind proxy
# Description
AuthController requires the $from parameter to be a url path, no hostname, because we only want to link back to our own site. However, in production, where the app is hosted behind a reverse proxy, a redirect to a path tries to send the browser to the backend url.
ie if you use `from=/en/admin` on the UAT server, you will be redirected to `http://uat-talentcloud-backend.tbs-sct.ca/en/admin` instead of `https://uat-talentcloud.tbs-sct.gc.ca/en/admin`, and this will result in a 403 error.

### PR DESCRIPTION
**Pull request by tristan-orourke**
Resolves #2044

Our app is hosted behind a proxy in production, so redirecting from the server to a url path won't work, we need to be able to add the domain of the frontend url.

I set the AuthController to use the root APP_URL instead of ADMIN_APP_URL, because the `from` parameter includes the entire domain, including the `/admin`. And since ADMIN_APP_URL wasn't being used anywhere else, I removed it from .env.example. I added an explicit APP_URL in .env.example, but it defaults to localhost in the config file, so the app should work even without changing your .env file.

One unfortunate consequence of this strategy is that if you navigate straight to `/admin/login` like we were doing before, without entering a from parameter, you will be redirected back to the main landing page, which can't actually process the access_token url parameter. This is less of a problem now that we have a login button which includes the from parameter for you, but I'm open to discussing alternatives with reviewers.

### CODE REVIEW

File: frontend/admin/app/Http/Controllers/AuthController.php [hunk 1]
```diff
@@ -70,7 +70,7 @@ public function authCallback(Request $request)
         if(substr($from, 0, 1) != '/')
             $from = null; // Does not start with / so it's not a relative url. Don't want an open redirect vulnerability. Throw it away.
 
-        $navigateToUri = strlen($from) > 0 ? $from : config('app.url');
+        $navigateToUri = strlen($from) > 0 ? config('app.url').$from : config('app.url');
```
Comment (petertgiles) [inline frontend/admin/app/Http/Controllers/AuthController.php:73]: Not being able to use a naked login link seems like a pretty big usability issue to me.  Would something like this solve it?
```suggestion
        $navigateToUri = strlen($from) > 0 ? config('app.url').$from : config('app.url').config('app.app_dir');
```

Comment (tristan-orourke) [reply frontend/admin/app/Http/Controllers/AuthController.php:73]: Yes, that works for now. We might need to rethink when we separate the auth code from the admin code (#1461) but that can be done later.

Comment (petertgiles) [reply frontend/admin/app/Http/Controllers/AuthController.php]: Agreed.  Maybe a redirect whitelist could be part of that conversation, too. (#1530)
