### PR TITLE
Bug - 4524 - Fix Storybook

### LINKED ISSUE #4524: Storybook 6.5.13 broken
## 👋 Introduction

Something broke with storybook...again.

## 🐛 Bug

It seems to have something to do with webpack.

### PR DESCRIPTION
**Pull request by esizer**
## 👋 Introduction

This bumps the storybook dependencies and fixes an issue with field error types in `react-hook-form`.

## ❓ What's Changed

- All storybook dependencies bumped to `6.5.13`
- `react-hook-form` bumped to `7.38.0`
- Adds `react-hook-form` error types
- Updates the storybook theme decorator to only apply `font-color` if `hasDarkMode` pref is `true`

## 🧪 Testing

> **Warning**
> Chromatic has no diff since main is broken. You will need to check the components.

1. Check to make sure chromatic built properly without errors
2. Run storybook locally and make sure no errors are present

## 🤖 Robot Stuff

Resolves #4524

### CODE REVIEW

File: frontend/common/src/components/inputPartials/InputError/InputError.tsx [hunk 1]
```diff
@@ -1,8 +1,17 @@
...
+  | FieldError
+  // This is from `react-hook-form` so ignore the any
+  // eslint-disable-next-line @typescript-eslint/no-explicit-any
+  | Merge<FieldError, FieldErrorsImpl<any>>
+  | undefined;
 
 export interface InputErrorProps {
   isVisible: boolean;
-  error: string;
+  error: InputErrorError;
```
Comment (petertgiles) [inline frontend/common/src/components/inputPartials/InputError/InputError.tsx:14]: Oh man, this type name is awful.  :laughing:  Would InputErrorMessage work or is that not accurate?  InputErrorReason?  InputErrorDetails?  InputErrorContext?

**Review by petertgiles — APPROVED** [review]
This looks great!  I confess that I don't really understand the problem or how you solved but I guess the InputError prop type change was key?  However it does build and run locally and Storybook builds fine, too.

File: frontend/common/src/components/inputPartials/InputError/InputError.tsx (hunk 1 above)
Comment (esizer) [reply frontend/common/src/components/inputPartials/InputError/InputError.tsx:14]: Lol yeah, agreed. What about `InputFieldError`? I struggled to find a name since it is just an error.

I wish `react-form-form` exported this type. 😞

**Comment by mnigh** [comment]
> This looks great!

@petertgiles don't forget to approve the UI Review, if possible? 
Screen Shot 2022-10-31 at 15 05 27

**Comment by petertgiles** [comment]
> @petertgiles don't forget to approve the UI Review, if possible?

Unfortunately, not possible in this one.  I do often forget though.  :laughing: 
image

**Comment by vd1992** [comment]
huh weird, storybook is working on Main again, it appears your earlier merge fixed it?
https://github.com/GCTC-NTGC/gc-digital-talent/actions/workflows/storybook.yml?query=branch%3Amain

😕

**Comment by esizer** [comment]
> huh weird, storybook is working on Main again, it appears your earlier merge fixed it?

That includes the `react-hook-form` bump fixing those issues. But, it does not include the `@storybook/*` bump which is what was broken.
