### PR TITLE
bug/4182 pool advertisement links dead

### LINKED ISSUE #4182: view pool advertisement button/link dead

### PR DESCRIPTION
**Pull request by vd1992**
closes #4182 
updates the link to the poster view
also cleans up a Todo or two in the same file

testing:
navigate to `/en/admin/pools/:id`
observe links

### CODE REVIEW

File: frontend/admin/src/js/components/pool/ViewPool.tsx [hunk 1]
```diff
@@ -112,6 +112,11 @@ export const ViewPoolPage = ({ pool }: ViewPoolPageProps): JSX.Element => {
     getSecurityClearance(pool.securityClearance ?? ""),
   );
 
+  const relativeToAbsoluteURL = (path: string): string => {
+    const { host } = window.location;
+    return `${host}${path}`;
```
Comment (esizer) [inline frontend/admin/src/js/components/pool/ViewPool.tsx:117]: Not sure about this, but maybe we could add the protocol? I don't think it is required since we seem to upgrade all `http` to `https`.

```suggestion
    const { host, protocol } = window.location;
    return `${protocol}//${host}${path}`;
```

**Review by esizer — APPROVED** [review]
Nice! 😄  One small suggestion about the `relativeToAbsoluteURL` function but not going to let that hold this up if you disagree

File: frontend/admin/src/js/components/pool/ViewPool.tsx (hunk 1 above)
Comment (vd1992) [reply frontend/admin/src/js/components/pool/ViewPool.tsx:117]: I have no strong feelings either way, so, sure!
