### PR TITLE
[Bug] Homepage Design Cleanup

### LINKED ISSUE #12816: Homepage design clean-up and changes
_Home page_
1. Card headers should be all the same size (see screenshot)
Screenshot 2025-02-20 at 11 25 56 AM
2. Vertical tablet view / small desktop view changes 
- Copy in "create a profile" section should span the entire width
Screenshot 2025-02-20 at 11 28 55 AM
- Content blocks and cards should stack vertically and span the whole page width
Screenshot 2025-02-20 at 11 37 12 AM
Screenshot 2025-02-20 at 11 38 42 AM
Screenshot 2025-02-20 at 11 37 23 AM

_Originally posted by @BrookeCameron in https://github.com/GCTC-NTGC/gc-digital-talent/issues/12789#issuecomment-2672054486_

### PR DESCRIPTION
**Pull request by bella77-69**
🤖 Resolves  #12816

👋 Introduction

This PR improves how things look and work on smaller screens. Card headers are now all the same size. In the "Create a Profile" section, the text now stretches across the full width on tablets and small desktops so it's easier to read. Content blocks and cards now stack vertically and take up the full width of the screen. Also, “Check it Out” cards now stack vertically when the title is short (less than 6 words).

🕵️ Details

- Made all card header text the same size
- Made the "Create a Profile" text full-width on vertical tablets and small desktops
- Updated content blocks and cards to stack and span the full width on smaller screens
- Changed layout for “Check it Out” cards so they stack when the title is short

🧪 Testing

1. Rebuild the app
2. Navigate through the home page and view on tablet and small desktop screen sizes
3. Check that the "Create a Profile" text goes across the full screen width
4. Make sure all card headers look the same size
5. Check that content blocks and cards are stacked and full-width on smaller screens
6. Look at “Check it Out” cards with short titles – they should stack vertically

 📸 Screenshot

image

https://github.com/user-attachments/assets/a268cac6-fd11-4084-bb5f-2a8355ba648d

https://github.com/user-attachments/assets/b25aee94-0952-47f3-a7f3-f2e450d251ab

https://github.com/user-attachments/assets/5d768638-1a95-4ecb-b831-0baf1b1c7ec6

https://github.com/user-attachments/assets/e1455397-865f-443c-bb47-d3bb2bcada37

### CODE REVIEW

File: apps/web/src/components/FeatureBlock/FeatureBlock.tsx [hunk 1]
```diff
@@ -42,14 +47,19 @@ const FeatureBlock = ({ content }: FeatureBlockProps) => {
...
+          src={content.img.path}
+          alt={content.title}
+          style={{
+            display: "block",
+            maxWidth: "100%",
+            height: "auto",
+            objectFit: "cover",
+            objectPosition: content.img.position ?? "center center",
+          }}
+        />
```
Comment (esizer) [inline apps/web/src/components/FeatureBlock/FeatureBlock.tsx:61]: This works well, I think we should probably aim to use hydrogen here where we can though.

```tsx
<img
   data-h2-display="base(block)"
   data-h2-max-width="base(100%)"
   data-h2-height="base(auto)"
   data-h2-object-fit="base(cover)"
/>
```

**Review by esizer — CHANGES_REQUESTED** [review]
Code is looking good, just one suggestion to prefer hydrogen over inline styles. I leave the design approval for @BrookeCameron :+1:

File: apps/web/src/components/FeatureBlock/FeatureBlock.tsx (hunk 1 above)
Comment (bella77-69) [reply apps/web/src/components/FeatureBlock/FeatureBlock.tsx:61]: Sounds good Thanks Eric!

Comment (esizer) [reply apps/web/src/components/FeatureBlock/FeatureBlock.tsx]: Oops, sorry. I forgot to mention we need to keep the object position one :sweat: Should be able to bring back:

```
style={{ objectPosition: content.img.position ?? "center center", }}
```

**Review by esizer — APPROVED** [review]

**Comment by BrookeCameron** [comment]
this looks great! Approved from my side.
