### PR TITLE
Bug - 3580 - Fix Pool Validation

### LINKED ISSUE #3580: Can't update a Pool with Remote Work Allowed
Validation fails when updating a pool unless I set specific locations. Spun off of https://github.com/GCTC-NTGC/gc-digital-talent/pull/3568#issuecomment-1205657235.

https://recordit.co/qEfDT4YLnv

Seems like a problem with the validator though. Or maybe we're submitting empty strings instead of nulls for locations?
```
{
  "errors": [
    {
      "message": "validation.string",
      "extensions": {
        "validation": {
          "advertisement_location.en": [
            "validation.string"
          ],
          "advertisement_location.fr": [
            "validation.string"
          ]
        },
        "category": "validation"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "publishPoolAdvertisement"
      ],
      "trace": [
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Auth\/CanDirective.php",
          "line": 151,
          "call": "App\\GraphQL\\Mutations\\PublishPoolAdvertisement::__invoke(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Auth\/GuardDirective.php",
          "line": 69,
          "call": "Nuwave\\Lighthouse\\Auth\\CanDirective::Nuwave\\Lighthouse\\Auth\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Schema\/Directives\/RenameArgsDirective.php",
          "line": 35,
          "call": "Nuwave\\Lighthouse\\Auth\\GuardDirective::Nuwave\\Lighthouse\\Auth\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Schema\/Directives\/SpreadDirective.php",
          "line": 34,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\RenameArgsDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Schema\/Directives\/ArgTraversalDirective.php",
          "line": 27,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\SpreadDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Validation\/ValidateDirective.php",
          "line": 50,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\ArgTraversalDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Schema\/Directives\/ArgTraversalDirective.php",
          "line": 27,
          "call": "Nuwave\\Lighthouse\\Validation\\ValidateDirective::Nuwave\\Lighthouse\\Validation\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Schema\/Directives\/TrimDirective.php",
          "line": 54,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\ArgTraversalDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Schema\/Factories\/FieldFactory.php",
          "line": 97,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\TrimDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/Executor\/ReferenceExecutor.php",
          "line": 623,
          "call": "Nuwave\\Lighthouse\\Schema\\Factories\\FieldFactory::Nuwave\\Lighthouse\\Schema\\Factories\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/Executor\/ReferenceExecutor.php",
          "line": 550,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveFieldValueOrError(instance of GraphQL\\Type\\Definition\\FieldDefinition, instance of GraphQL\\Language\\AST\\FieldNode, instance of Closure, null, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/Executor\/ReferenceExecutor.php",
          "line": 474,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveField(GraphQLType: Mutation, null, instance of ArrayObject(1), array(1))"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/Executor\/ReferenceExecutor.php",
          "line": 857,
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'publishPoolAdvertisement')"
        },
        {
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'publishPoolAdvertisement')"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/Executor\/ReferenceExecutor.php",
          "line": 859,
          "function": "array_reduce(array(1), instance of Closure, array(0))"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/Executor\/ReferenceExecutor.php",
          "line": 490,
          "call": "GraphQL\\Executor\\ReferenceExecutor::promiseReduce(array(1), instance of Closure, array(0))"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/Executor\/ReferenceExecutor.php",
          "line": 263,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeFieldsSerially(GraphQLType: Mutation, null, array(0), instance of ArrayObject(1))"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/Executor\/ReferenceExecutor.php",
          "line": 215,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeOperation(instance of GraphQL\\Language\\AST\\OperationDefinitionNode, null)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/Executor\/Executor.php",
          "line": 156,
          "call": "GraphQL\\Executor\\ReferenceExecutor::doExecute()"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/GraphQL.php",
          "line": 162,
          "call": "GraphQL\\Executor\\Executor::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, instance of GraphQL\\Language\\AST\\DocumentNode, null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(1), 'publishPoolAdvertisement', null)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/GraphQL.php",
          "line": 94,
          "call": "GraphQL\\GraphQL::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, instance of GraphQL\\Language\\AST\\DocumentNode, null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(1), 'publishPoolAdvertisement', null, array(29))"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/GraphQL.php",
          "line": 268,
          "call": "GraphQL\\GraphQL::executeQuery(instance of GraphQL\\Type\\Schema, instance of GraphQL\\Language\\AST\\DocumentNode, null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(1), 'publishPoolAdvertisement', null, array(29))"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/GraphQL.php",
          "line": 203,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeParsedQuery(instance of GraphQL\\Language\\AST\\DocumentNode, instance of Nuwave\\Lighthouse\\Schema\\Context, array(1), null, 'publishPoolAdvertisement')"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/GraphQL.php",
          "line": 162,
          "call": "Nuwave\\Lighthouse\\GraphQL::parseAndExecuteQuery('mutation publishPoolAdvertisement($id: ID!) {\n  publishPoolAdvertisement(id: $id) {\n    isPublished\n    __typename\n  }\n}', instance of Nuwave\\Lighthouse\\Schema\\Context, array(1), null, 'publishPoolAdvertisement')"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/GraphQL.php",
          "line": 121,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeOperation(instance of GraphQL\\Server\\OperationParams, instance of Nuwave\\Lighthouse\\Schema\\Context)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Support\/Utils.php",
          "line": 99,
          "call": "Nuwave\\Lighthouse\\GraphQL::Nuwave\\Lighthouse\\{closure}(instance of GraphQL\\Server\\OperationParams)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/GraphQL.php",
          "line": 120,
          "call": "Nuwave\\Lighthouse\\Support\\Utils::mapEach(instance of Closure, instance of GraphQL\\Server\\OperationParams)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Support\/Http\/Controllers\/GraphQLController.php",
          "line": 32,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeOperationOrOperations(instance of GraphQL\\Server\\OperationParams, instance of Nuwave\\Lighthouse\\Schema\\Context)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php",
          "line": 48,
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController::__invoke(instance of Illuminate\\Http\\Request, instance of Nuwave\\Lighthouse\\GraphQL, instance of Illuminate\\Events\\Dispatcher, instance of Laragraph\\Utils\\RequestParser, instance of Nuwave\\Lighthouse\\Execution\\SingleResponse, instance of Nuwave\\Lighthouse\\Execution\\ContextFactory)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php",
          "line": 262,
          "call": "Illuminate\\Routing\\ControllerDispatcher::dispatch(instance of Illuminate\\Routing\\Route, instance of Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController, '__invoke')"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php",
          "line": 205,
          "call": "Illuminate\\Routing\\Route::runController()"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php",
          "line": 721,
          "call": "Illuminate\\Routing\\Route::run()"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 128,
          "call": "Illuminate\\Routing\\Router::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/app\/Http\/Middleware\/AuditQueryMiddleware.php",
          "line": 42,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 167,
          "call": "App\\Http\\Middleware\\AuditQueryMiddleware::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Support\/Http\/Middleware\/AttemptAuthentication.php",
          "line": 34,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 167,
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AttemptAuthentication::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Support\/Http\/Middleware\/AcceptJson.php",
          "line": 27,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 167,
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AcceptJson::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 103,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php",
          "line": 723,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php",
          "line": 698,
          "call": "Illuminate\\Routing\\Router::runRouteWithinStack(instance of Illuminate\\Routing\\Route, instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php",
          "line": 662,
          "call": "Illuminate\\Routing\\Router::runRoute(instance of Illuminate\\Http\\Request, instance of Illuminate\\Routing\\Route)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php",
          "line": 651,
          "call": "Illuminate\\Routing\\Router::dispatchToRoute(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php",
          "line": 167,
          "call": "Illuminate\\Routing\\Router::dispatch(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 128,
          "call": "Illuminate\\Foundation\\Http\\Kernel::Illuminate\\Foundation\\Http\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ConvertEmptyStringsToNull.php",
          "line": 31,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 167,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TrimStrings.php",
          "line": 40,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 167,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TrimStrings::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ValidatePostSize.php",
          "line": 27,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 167,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/PreventRequestsDuringMaintenance.php",
          "line": 86,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 167,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/fruitcake\/laravel-cors\/src\/HandleCors.php",
          "line": 38,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 167,
          "call": "Fruitcake\\Cors\\HandleCors::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Http\/Middleware\/TrustProxies.php",
          "line": 39,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 167,
          "call": "Illuminate\\Http\\Middleware\\TrustProxies::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 103,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php",
          "line": 142,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php",
          "line": 111,
          "call": "Illuminate\\Foundation\\Http\\Kernel::sendRequestThroughRouter(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/public\/index.php",
          "line": 52,
          "call": "Illuminate\\Foundation\\Http\\Kernel::handle(instance of Illuminate\\Http\\Request)"
        }
      ]
    }
  ],
  "data": {
    "publishPoolAdvertisement": null
  }
}
```

### PR DESCRIPTION
**Pull request by esizer**
Resolves #3580 

## Summary

This improves the validation for publishing a pool advertisement, fixing a problem with remote locations.

## What This Does

- Introduces a new boolean column in the `pools` table for `is_remote`
- Updates the Pool factory to include the new column
- Updates the valuation for the `publishPoolAdvertisement` mutation
  - `advertisement_location` now required when `is_remote` is `false`
- Updates the following pages to incorporate the new column
  - `/{locale}/admin/pools/{id}`
  - `/{locale}/admin/pools/{id}/edit`
  - `/{locale}/browse/pools/{id}/view`

### Rebuild PHP Container

1. `docker-compose stop php`
2. `docker-compose rm php`
3. `docker-compose up --build --detach`

### Publish Remote

1. Navigate to `/admin/pools`
2. Create a new Pool
3. Fill out all fields
  -  Make sure **Location** is set to **Remote Optional**
5. **Publish** the pool advertisement

## Publish Specific Location

1. Navigate to `/admin/pools`
2. Create a new Pool
3. Fill out all fields
  -  Make sure **Location** is set to **Specific Location**
  - Make sure to fill out the **Specific Location** text fields
5. **Publish** the pool advertisement

## Publish Specific Location (Error)

1. Navigate to `/admin/pools`
2. Create a new Pool
3. Fill out all fields
  -  Make sure **Location** is set to **Specific Location**
  - Make sure to **NOT** fill out the **Specific Location** text fields
5. **Publish** the pool advertisement

## Deployment Notes

This contains a **migration** that must be run when deployment.

### CODE REVIEW

File: api/database/migrations/2022_08_09_164050_add_is_remote_column_pools_table.php [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+{
+    /**
+     * Run the migrations.
+     *
+     * @return void
+     */
+    public function up()
+    {
+        Schema::table('pools', function (Blueprint $table) {
+            $table->boolean('is_remote')->default(false)->after('advertisement_location');
```
Comment (petertgiles) [inline api/database/migrations/2022_08_09_164050_add_is_remote_column_pools_table.php:17]: I think this should be nullable?  Or should it be not-nullable in the schema?

File: frontend/admin/src/js/components/pool/EditPool/OtherRequirementsSection.tsx [hunk 2]
```diff
@@ -9,6 +9,7 @@ import {
   getLanguageRequirement,
   getSecurityClearance,
 } from "@common/constants/localizedConstants";
+import { notEmpty } from "@common/helpers/util";
```
Comment (petertgiles) [inline frontend/admin/src/js/components/pool/EditPool/OtherRequirementsSection.tsx:12]: Unused imports `isEmpty` and `notEmtpy`

File: frontend/admin/src/js/components/pool/EditPool/OtherRequirementsSection.tsx [hunk 3]
```diff
@@ -82,8 +84,8 @@ export const OtherRequirementsSection = ({
     if (formValues.locationOption === LocationOption.RemoteOptional) {
       return {
         ...formValues,
-        specificLocationEn: null,
-        specificLocationFr: null,
+        specificLocationEn: undefined,
```
Comment (petertgiles) [inline frontend/admin/src/js/components/pool/EditPool/OtherRequirementsSection.tsx:87]: I think these need to actually be null or else it won't blank out the locations when you switch it to "remote".  This leaves the databse in an inconsistent state.
image

**Review by petertgiles — CHANGES_REQUESTED** [review]
This is a big improvement!  A few small things to check below.

File: api/database/migrations/2022_08_09_164050_add_is_remote_column_pools_table.php (hunk 1 above)
Comment (esizer) [reply api/database/migrations/2022_08_09_164050_add_is_remote_column_pools_table.php:17]: I'm actually not sure. My reasoning is that the position has to be remote or not and there is no real in between (null). Unless we treat null as not remote as well.

File: frontend/admin/src/js/components/pool/EditPool/OtherRequirementsSection.tsx (hunk 2 above)
Comment (esizer) [reply frontend/admin/src/js/components/pool/EditPool/OtherRequirementsSection.tsx]: Fixed with [remove unused imports](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3644/commits/1fead82973ea81de67acd27a35ecc19cb3806fad)

File: frontend/admin/src/js/components/pool/EditPool/OtherRequirementsSection.tsx (hunk 3 above)
Comment (esizer) [reply frontend/admin/src/js/components/pool/EditPool/OtherRequirementsSection.tsx]: Nice catch, update in [null location name if is remote](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3644/commits/9f80072d1de7bb36ef69e5ae38b8909ac8b4db39)

File: api/database/migrations/2022_08_09_164050_add_is_remote_column_pools_table.php (hunk 1 above)
Comment (petertgiles) [reply api/database/migrations/2022_08_09_164050_add_is_remote_column_pools_table.php:17]: Graphql tends to prefer nullable fields and therefore most of our database columns are also nullable.  It also using the muation as a "patch" with only some fields and allows us to force users to answer yes/no questions without making an assumption.  I'd recommend making it nullable and then making it a required field on the form.

Comment (esizer) [reply api/database/migrations/2022_08_09_164050_add_is_remote_column_pools_table.php]: Okay, I have made it nullable in [make is_remote nullable](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3644/commits/4f61b22330e569c44c580419bacd2d0e612975d8). I also updated the publish validation to require this field now to prevent publishing when this field has not been selected.

The form still has this field marked as optional though since I'm not certain of the outcome of the discussion we had regarding which fields should be required while editing the pools. However, since it is a radio button, it would be very difficult for someone to submit the form without setting true/false.

**Review by petertgiles — APPROVED** [review]
